
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FileServerWSService", targetNamespace = "http://trab1/", wsdlLocation = "http://192.168.1.4:8080/FileServer?wsdl")
public class FileServerWSService
    extends Service
{

    private final static URL FILESERVERWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ws.FileServerWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ws.FileServerWSService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.1.4:8080/FileServer?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.1.4:8080/FileServer?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FILESERVERWSSERVICE_WSDL_LOCATION = url;
    }

    public FileServerWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileServerWSService() {
        super(FILESERVERWSSERVICE_WSDL_LOCATION, new QName("http://trab1/", "FileServerWSService"));
    }

    /**
     * 
     * @return
     *     returns FileServerWS
     */
    @WebEndpoint(name = "FileServerWSPort")
    public FileServerWS getFileServerWSPort() {
        return super.getPort(new QName("http://trab1/", "FileServerWSPort"), FileServerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileServerWS
     */
    @WebEndpoint(name = "FileServerWSPort")
    public FileServerWS getFileServerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://trab1/", "FileServerWSPort"), FileServerWS.class, features);
    }

}
