
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FileServerWS", targetNamespace = "http://trab1/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileServerWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mkdir", targetNamespace = "http://trab1/", className = "ws.Mkdir")
    @ResponseWrapper(localName = "mkdirResponse", targetNamespace = "http://trab1/", className = "ws.MkdirResponse")
    public boolean mkdir(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws InfoNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dir", targetNamespace = "http://trab1/", className = "ws.Dir")
    @ResponseWrapper(localName = "dirResponse", targetNamespace = "http://trab1/", className = "ws.DirResponse")
    public List<String> dir(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws InfoNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rmdir", targetNamespace = "http://trab1/", className = "ws.Rmdir")
    @ResponseWrapper(localName = "rmdirResponse", targetNamespace = "http://trab1/", className = "ws.RmdirResponse")
    public boolean rmdir(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rm", targetNamespace = "http://trab1/", className = "ws.Rm")
    @ResponseWrapper(localName = "rmResponse", targetNamespace = "http://trab1/", className = "ws.RmResponse")
    public boolean rm(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.FileInfo
     * @throws InfoNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAttr", targetNamespace = "http://trab1/", className = "ws.GetAttr")
    @ResponseWrapper(localName = "getAttrResponse", targetNamespace = "http://trab1/", className = "ws.GetAttrResponse")
    public FileInfo getAttr(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws InfoNotFoundException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pasteFile", targetNamespace = "http://trab1/", className = "ws.PasteFile")
    @ResponseWrapper(localName = "pasteFileResponse", targetNamespace = "http://trab1/", className = "ws.PasteFileResponse")
    public boolean pasteFile(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "copyFile", targetNamespace = "http://trab1/", className = "ws.CopyFile")
    @ResponseWrapper(localName = "copyFileResponse", targetNamespace = "http://trab1/", className = "ws.CopyFileResponse")
    public byte[] copyFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

}
